// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iuyontcutlmzcmkqwnan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1eW9udGN1dGxtemNta3F3bmFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NjY1NDUsImV4cCI6MjA3NDQ0MjU0NX0.p00VUDxxCF7GW5N8Jl_7Q-JhnGX61-FgpQyFuUgIiwQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});